export default {
  CREATE_TRANSACTION: 'CREATE_TRANSACTION',
  UPDATE_TRANSACTION: 'UPDATE_TRANSACTION',
  DELETE_TRANSACTION: 'DELETE_TRANSACTION',
  ADD_TRANSACTION_TO_FAVOURITE: 'ADD_TRANSACTION_TO_FAVOURITE',
};
