export default {
  LOGIN_USER_START: 'LOGIN_USER_START',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',

  LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS',

  BACKUP_START: 'BACKUP_START',
  BACKUP_SUCCESS: 'BACKUP_SUCCESS',
  BACKUP_ERROR: ' BACKUP_ERROR',


  SYNCHRONIZATION_START: 'SYNCHRONIZATION_START',
  SYNCHRONIZATION_SUCCESS: 'SYNCHRONIZATION_SUCCESS',
  SYNCHRONIZATION_ERROR: 'SYNCHRONIZATION_ERROR',
};
