export default [
  { value: 10, account: 0, category: 0, note: 'test note' },
  { value: 20, account: 0, category: 1, note: 'test note' },
  { value: 30, account: 0, category: 0, note: 'test note' },
  { value: 10, account: 0, category: 1, note: 'test note' },
  { value: 30, account: 0, category: 4, note: 'test note' },
  { value: 10, account: 0, category: 4, note: 'test note' },
  { value: 20, account: 0, category: 0, note: 'test note' },
  { value: 30, account: 0, category: 1, note: 'test note' },
  { value: 10, account: 0, category: 0, note: 'test note' },
  { value: 20, account: 0, category: 1, note: 'test note' },
  { value: 30, account: 0, category: 0, note: 'test note' },
  { value: 10, account: 0, category: 1, note: 'test note' },
  { value: 20, account: 0, category: 0, note: 'test note' },
  { value: 30, account: 0, category: 1, note: 'test note' },
  { value: 20, account: 0, category: 4, note: 'test note' },
  { value: 30, account: 0, category: 4, note: 'test note' },
];
