export default [
  [
    { type: 'income', value: 1000 },
    { type: 'income', value: 1200 },
    { type: 'income', value: 1100 },
    { type: 'income', value: 1000 },
    // { type: 'income', value: 1200 },
    // { type: 'income', value: 1100 },
    // { type: 'income', value: 1000 },
    // { type: 'income', value: 1200 },
    // { type: 'income', value: 1100 },
    // { type: 'income', value: 1000 },
    // { type: 'income', value: 1200 },
    // { type: 'income', value: 1100 },
  ],
  [
    { type: 'expense', value: 800 },
    { type: 'expense', value: 900 },
    { type: 'expense', value: 700 },
    { type: 'expense', value: 800 },
    // { type: 'expense', value: 900 },
    // { type: 'expense', value: 700 },
    // { type: 'expense', value: 800 },
    // { type: 'expense', value: 900 },
    // { type: 'expense', value: 700 },
    // { type: 'expense', value: 800 },
    // { type: 'expense', value: 900 },
    // { type: 'expense', value: 700 },
  ],
];
