export const CHANGE_DEFAULT_CURRENCY = 'CHANGE_DEFAULT_CURRENCY';
export const UPDATE_ACCOUNT_FIELD = 'UPDATE_ACCOUNT_FIELD';
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const CLEAR_ACCOUNT_FORM = 'CLEAR_ACCOUNT_FORM';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
